config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/users', to: "users#index"
  # get '/users/new', to: "users#new"
  # post '/users', to: "users#create"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render template: 'layouts/header' %>
    <%= yield :header %>
    <%= yield :footer %>
    <%= render template: 'layouts/footer' %>
  </body>
</html>

app/views/users/_form.html.erb
<h1><%= title %></h1>

<%= form_with model: @user do |f| %>
  <div class="mb-3">
    <%= f.label :name, 'Họ và tên', class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :email, 'Email', class: 'form-label' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :dob, 'Ngày sinh', class: 'form-label' %>
    <%= f.date_field :dob, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :address, 'Địa chỉ', class: 'form-label' %>
    <%= f.text_area :address, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :phone, 'Số điện thoại', class: 'form-label' %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <div class="form-check">
      <%= f.radio_button :gender, 1, class: 'form-check-input', checked: true %>
      <%= f.label :gender, 'Nam', class: 'form-check-label' %>
    </div>

    <div class="form-check">
      <%= f.radio_button :gender, 0, class: 'form-check-input' %>
      <%= f.label :gender, 'Nữ', class: 'form-check-label'%>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :vacine, 'Trạng thái tiêm vacine', class: 'form-check-label'%>
    <%= f.select :vacine, [['Đã tiêm vacine', true], ['Chưa tiêm vacine', false]], {}, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <% Language.all.each do |language| %>
      <div class='row'>
        <label>
          <%= f.check_box :language, { multiple: true }, language.id, nil %>
          <%= language.name %>
        </label>
      </div>
    <% end %>
  </div>

  <%= f.submit 'Đăng ký', class: 'btn btn-success' %>

  <% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<div class="container" style='width: 1000px'>
  <%= render partial: 'form', locals: { title: 'Huong dan tao form' } %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>